swagger: "2.0"
info:
    version: "0.0.1"
    title: VCAPI.Server
# during dev, should point to your local machine
host: localhost:10011
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
    # tip: remove http to make production-grade
    - http
    - https
# format of bodies a client can send (Content-Type)
consumes:
    - application/json
# format of the responses to the client (Accepts)
produces:
    - application/json
paths:
    $ref: ./api/swagger/routes.yaml
    /swagger:
        x-swagger-pipe: swagger_raw
definitions:
    $ref: ./api/swagger/definitions.yaml
